"
I am a presenter to do actions during a debugging session with a DAPClient. 
"
Class {
	#name : 'ClientDAPPresenter',
	#superclass : 'SpPresenter',
	#traits : 'DAPObserver',
	#classTraits : 'DAPObserver classTrait',
	#instVars : [
		'commandBarPresenter',
		'requestPresenter',
		'responsePresenter',
		'clientDAP',
		'messageListPresenter'
	],
	#category : 'PharoDAPClient-Presenters',
	#package : 'PharoDAPClient',
	#tag : 'Presenters'
}

{ #category : 'instance creation' }
ClientDAPPresenter class >> newWithClient: aDAPClient [
	
	^ self new clientDAP: aDAPClient 
]

{ #category : 'helpers' }
ClientDAPPresenter >> addCommand: label iconName: iconName ask: question do: selector [

	commandBarPresenter addItem: (self newToolbarButton
			 label: label;
			 icon: (self iconNamed: iconName);
			 action: [
					 self
						 askInteger: question
						 do: [ :val | self perform: selector with: val ] ];
			 yourself)
]

{ #category : 'helpers' }
ClientDAPPresenter >> addCommand: label iconName: iconName do: selector [

	commandBarPresenter addItem: (self newToolbarButton
			 label: label;
			 icon: (self iconNamed: iconName);
			 action: [ self perform: selector ];
			 yourself)
]

{ #category : 'helpers' }
ClientDAPPresenter >> askInteger: aLabel do: aBlock [

	| input value |
	input := UIManager default request: aLabel.

	input ifNil: [ ^ self ].

	value := [ input asInteger ]
		         on: Error
		         do: [ ^ self ].

	value ifNotNil: [ aBlock value: value ]
]

{ #category : 'accessing' }
ClientDAPPresenter >> clientDAP [

	^ clientDAP
]

{ #category : 'accessing' }
ClientDAPPresenter >> clientDAP: aDAPClient [
	
	clientDAP := aDAPClient.
	clientDAP dapHistory addObserver: self.
	self updateMessageList
]

{ #category : 'commands' }
ClientDAPPresenter >> closeConnection [

	clientDAP closeConnection
]

{ #category : 'helpers' }
ClientDAPPresenter >> colorForMessage: messageAsDict [

	| type |
	type := messageAsDict at: #type.

	type = 'request' ifTrue: [ ^ Color lightBlue ].
	type = 'response' ifTrue: [
			(messageAsDict at: #success) ifTrue: [ ^ Color lightGreen ].
			^ Color red ].
	type = 'event' ifTrue: [ ^ Color lightOrange ].

	^ Color white
]

{ #category : 'commands' }
ClientDAPPresenter >> continue [

	[ clientDAP continue ] fork
]

{ #category : 'commands' }
ClientDAPPresenter >> continue: aThreadId [

	| args |
	args := DAPContinueArguments new threadId: aThreadId.
	clientDAP continue: args
]

{ #category : 'commands' }
ClientDAPPresenter >> dataBreakpointInfo: frameId [

	| args |
	self halt.
	args := DAPDataBreakpointInfoArguments new
		        variablesReference: 4;
		        frameId: frameId;
		        name: 'str'.

	clientDAP dataBreakpointInfo: args
]

{ #category : 'layout' }
ClientDAPPresenter >> defaultLayout [

	^ SpBoxLayout newTopToBottom
		  add: #commandBarPresenter height: 40;
		  add: (SpPanedLayout newLeftToRight
				   add: #messageListPresenter;
				   add: (SpPanedLayout newTopToBottom
						    add: #requestPresenter;
						    add: #responsePresenter;
						    yourself);
				   positionOfSlider: 300;
				   yourself);
		  yourself
]

{ #category : 'update' }
ClientDAPPresenter >> displayEvent: aDAPEvent [

	aDAPEvent ifNil: [ ^ self ].
	responsePresenter text:
		(STONJSON toStringPretty: aDAPEvent asDAPJSON).
	requestPresenter text: ''
]

{ #category : 'update' }
ClientDAPPresenter >> displayMessage: messageAsDict [

	| type |
	messageAsDict ifNil: [ ^ self ].
	type := messageAsDict at: 'type'.
	type = #request ifTrue: [ self displayRequest: messageAsDict ].
	type = #event ifTrue: [ self displayEvent: messageAsDict ].
	type = #response ifTrue: [ self displayResponse: messageAsDict ]
]

{ #category : 'update' }
ClientDAPPresenter >> displayRequest: aDAPRequest [

	| response |
	aDAPRequest ifNil: [ ^ self ].

	requestPresenter text: (STONJSON toStringPretty: aDAPRequest asDAPJSON ).

	response := clientDAP dapHistory responseForRequest: (aDAPRequest at: #seq).

	responsePresenter text: (response
			 ifNil: [ '' ]
			 ifNotNil: [ STONJSON toStringPretty: response asDAPJSON ])
]

{ #category : 'update' }
ClientDAPPresenter >> displayResponse: responseAsDict [

	| request |
	responseAsDict ifNil: [ ^ self ].
	
	responsePresenter text: (STONJSON toStringPretty: responseAsDict asDAPJSON ).

	request := clientDAP dapHistory request: (responseAsDict at: #request_seq).

	requestPresenter text: (request
			 ifNil: [ '' ]
			 ifNotNil: [ STONJSON toStringPretty: request asDAPJSON ])
]

{ #category : 'commands' }
ClientDAPPresenter >> evaluate: frameId [

	| args |
	self halt.
	args := DAPEvaluateArguments new
		        context: 'repl';
		        frameId: frameId;
		        expression:
			        'foo'.

	clientDAP evaluate: args
]

{ #category : 'commands' }
ClientDAPPresenter >> goto: targetId [
	
	| args |
	args := DAPGotoArguments new
		targetId: targetId;
		threadId: 1.
	clientDAP goto: args
]

{ #category : 'commands' }
ClientDAPPresenter >> gotoTarget: line [
	
	| args |
	args := DAPGotoTargetsArguments new
		source: (DAPSource new path: '/Users/flavienvolant/Documents/sindarin-dap/py/script.py');
		line: line.
	clientDAP gotoTarget: args
]

{ #category : 'initialization' }
ClientDAPPresenter >> initializeCommandBar [
	
	commandBarPresenter := self newToolbar.
	
	self addCommand: 'Threads' iconName: #trait do: #threads. 
	self addCommand: 'Stack Trace' iconName: #browse do: #stackTrace.
	self addCommand: 'Scopes' iconName: #folder ask: 'Frame Id ?' do: #scopes:.
	self addCommand: 'Variables' iconName: #table ask: 'Variables Reference ?' do: #variables:.
	self addCommand: 'Continue' iconName: #go do: #continue.
	self addCommand: 'Next' iconName: #right do: #next.
	self addCommand: 'Step In' iconName: #into do: #stepInDAP.
	self addCommand: 'Step Out' iconName: #over do: #stepOut.
	self addCommand: 'Evaluate' iconName: #browse ask: 'Frame Id ?' do: #evaluate:.
	self addCommand: 'Set Expression' iconName: #edit  ask: 'Frame Id ?' do: #setExpression:. 
	self addCommand: 'Goto Target' iconName: #hierarchy ask: 'Line ?' do: #gotoTarget:.
	self addCommand: 'Goto' iconName: #references ask: 'Goto Target Id ?' do: #goto:. 
	self addCommand: 'Step In Targets' iconName: #branch ask: 'Frame Id ?' do: #stepInTargets:.
	self addCommand: 'Data Breakpoint Info' iconName: #database ask: 'Frame Id ?' do: #dataBreakpointInfo:.
	self addCommand: 'Data Breakpoint' iconName: #databaseAdd do: #setDataBreakpoint .
	self addCommand: 'Disconnect' iconName: #close do: #closeConnection
]

{ #category : 'initialization' }
ClientDAPPresenter >> initializeDapRegistry [

	self clientDAP initializeDapRegistry
]

{ #category : 'initialization' }
ClientDAPPresenter >> initializeMessageList [

	messageListPresenter := self newTable.

	messageListPresenter
		addColumn: ((SpStringTableColumn
				  title: 'Seq'
				  evaluated: [ :item | item at: 'seq' ifAbsent: [ '' ] ]) width:
					 40);
		addColumn: ((SpStringTableColumn
				  title: 'Type'
				  evaluated: [ :item | item at: 'type' ifAbsent: [ '' ] ])
				 width: 80;
				 displayColor: [ :item | self colorForMessage: item ]);
		addColumn: (SpStringTableColumn title: 'Name' evaluated: [ :item |
				 item
					 at: 'event'
					 ifAbsent: [ item at: 'command' ifAbsent: [ '' ] ] ]);
		whenSelectionChangedDo: [ :selection |
		self displayMessage: selection selectedItem ]
]

{ #category : 'initialization' }
ClientDAPPresenter >> initializePresenters [

	self initializeCommandBar.
	self initializeMessageList.
	self initializeRequest.
	self initializeResponse
]

{ #category : 'initialization' }
ClientDAPPresenter >> initializeRequest [

	requestPresenter := self newText.
	requestPresenter beNotEditable
]

{ #category : 'initialization' }
ClientDAPPresenter >> initializeResponse [

	responsePresenter := self newText.
	responsePresenter beNotEditable
]

{ #category : 'initialization' }
ClientDAPPresenter >> initializeWindow: aWindowPresenter [
	
	super initializeWindow: aWindowPresenter.
	aWindowPresenter 
		title: 'Client DAP';
		initialExtent: 800@400
]

{ #category : 'commands' }
ClientDAPPresenter >> next [

	self next: 1
]

{ #category : 'commands' }
ClientDAPPresenter >> next: aThreadId [

	| args |
	args := DAPNextArguments new threadId: aThreadId.
	clientDAP next: args
]

{ #category : 'initialization' }
ClientDAPPresenter >> open [

	| window |
	window := super open.
	window whenClosedDo: [ self closeConnection ]
]

{ #category : 'commands' }
ClientDAPPresenter >> scopes: aFrameId [

	| args |
	args := DAPScopesArguments new frameId: aFrameId.
	clientDAP scopes: args
]

{ #category : 'commands' }
ClientDAPPresenter >> setDataBreakpoint [

	| args |
	self halt.
	args := DAPSetDataBreakpointsArguments new breakpoints:
		        { (DAPDataBreakpoint new
			         dataId: 'example.Bar#str';
			         accessType: 'readWrite') }.

	clientDAP setDataBreakPoints: args
]

{ #category : 'commands' }
ClientDAPPresenter >> setExpression: aFramedId [

	| args |
	self halt.
	args := DAPSetExpressionArguments new
		        expression: '__instance_to_follow_1__';
		        value: 'bar';
		        frameId: aFramedId.

	clientDAP setExpression: args
]

{ #category : 'commands' }
ClientDAPPresenter >> stackTrace [

	self stackTrace: 1
]

{ #category : 'commands' }
ClientDAPPresenter >> stackTrace: aThreadId [

	self stackTrace: aThreadId onResponse: [ :resp |  ]
]

{ #category : 'commands' }
ClientDAPPresenter >> stackTrace: aThreadId onResponse: aBlock [

	| args |
	args := DAPStackTraceArguments new
		        threadId: aThreadId;
		        format: { (#module -> true) } asDictionary;
		        yourself.

	clientDAP stackTrace: args onResponse: aBlock
]

{ #category : 'commands' }
ClientDAPPresenter >> stepInDAP [

	self stepInDAP: 1
]

{ #category : 'commands' }
ClientDAPPresenter >> stepInDAP: aThreadId [

	| args |
	args := DAPStepInArguments new threadId: aThreadId.
	clientDAP stepIn: args
]

{ #category : 'commands' }
ClientDAPPresenter >> stepInTargets: frameId [

	| args |
	args := DAPStepInTargetsArguments new frameId: frameId.
	clientDAP stepInTargets: args
]

{ #category : 'commands' }
ClientDAPPresenter >> stepOut [
	
	self stepOut: 1
]

{ #category : 'commands' }
ClientDAPPresenter >> stepOut: aThreadId [

	| args |
	args := DAPStepOutArguments new threadId: aThreadId.
	clientDAP stepOut: args
]

{ #category : 'commands' }
ClientDAPPresenter >> threads [

	clientDAP threads
]

{ #category : 'update' }
ClientDAPPresenter >> updateMessageList [

	messageListPresenter items:
		clientDAP dapHistory messages.
	messageListPresenter refresh
]

{ #category : 'event handling' }
ClientDAPPresenter >> updateWithEvent: aDAPEvent [

	self updateMessageList 
]

{ #category : 'event handling' }
ClientDAPPresenter >> updateWithRequest: aDAPRequest [
	
	self updateMessageList 
]

{ #category : 'event handling' }
ClientDAPPresenter >> updateWithResponse: aDAPResponse [

	self updateMessageList
]

{ #category : 'commands' }
ClientDAPPresenter >> variables: aVariablesReference [

	| args |
	args := DAPVariablesArguments new variablesReference:
		        aVariablesReference.
	clientDAP variables: args
]
