Class {
	#name : 'DAPClientForPY',
	#superclass : 'SindarinDAPClient',
	#category : 'PharoDAPClient-Examples',
	#package : 'PharoDAPClient',
	#tag : 'Examples'
}

{ #category : 'initialization' }
DAPClientForPY >> attachArguments [

	^ {
		  ('name' -> 'Attach to Python').
		  ('type' -> 'python').
		  ('connect' -> {
			   ('host' -> 'localhost').
			   ('port' -> 5678) } asDictionary).
		  ('redirectOutput' -> true).
		  ('showReturnValue' -> true).
		  ('justMyCode' -> false) } asDictionary
]

{ #category : 'initialization' }
DAPClientForPY >> initialize [

	super initialize.

	DAPClientBuilder new
		client: self;
		port: 5678;
		adapterID: 'python';
		attachArguments: self attachArguments;
		breakpoint:
			'/Users/flavienvolant/Documents/sindarin-dap/py/script.py'
		line: 10;
		backend: DAPBackendPY new;
		startClientSession
]

{ #category : 'stack access' }
DAPClientForPY >> variablesForObject: aVariableName inStackFrame: frameId [

	| specialVariablesReference |
	specialVariablesReference := (super
		                              variablesForObject: aVariableName
		                              inStackFrame: frameId) first at:
		                             'variablesReference'.
	^ self variablesForReference: specialVariablesReference
]
